spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://registry-registry-service:8081/eureka
service:
  product: http://product-product-service:8083
  user: http://user-user-service:8084
  sale: http://sale-sale-service:8085
  order: http://order-order-service:8086
